// Bilingual content data for EgyGulf Foods site
const SITE_DATA = {
  events: [
    { image:'images/events/event-3.jpg', position:'center 15%',
      title:{ar:'جناحنا في المعرض', en:'Our Booth at the Expo'},
      sub:{ar:'ChillOut وLight Pop على واجهة الجناح', en:'ChillOut and Light Pop on display at our stand'} },
    { image:'images/events/event-2.jpg', position:'center 20%',
      title:{ar:'لقاء تليفزيوني مع قناة النهار', en:'TV Interview with Al Nahar'},
      sub:{ar:'حديث عن منتجاتنا وخطط التوسع', en:'Discussing our products and expansion plans'} },
    { image:'images/events/event-1.jpg', position:'center 35%',
      title:{ar:'اجتماع مع أحد الموزعين', en:'Meeting with a Distributor'},
      sub:{ar:'مناقشة تفاصيل التعاون على هامش المعرض', en:'Working out partnership details on the sidelines'} },
    { image:'images/events/event-4.jpg', position:'center 40%',
      title:{ar:'جولة على أجنحة المعرض', en:'Touring the Exhibition Halls'},
      sub:{ar:'تواصل مباشر مع العارضين وشركاء الصناعة', en:'Connecting with exhibitors and industry partners'} },
    { image:'images/events/event-5.jpg', position:'center 30%',
      title:{ar:'لقاءات وشراكات جديدة', en:'New Meetings and Partnerships'},
      sub:{ar:'تبادل الخبرات مع زملاء الصناعة', en:'Exchanging insight with industry peers'} },
    { image:'images/events/event-6.jpg', position:'center 30%',
      title:{ar:'نقاشات على هامش الفعالية', en:'Conversations on the Sidelines'},
      sub:{ar:'فريق العمل في حوار مع زوار المعرض', en:'Our team in discussion with expo visitors'} },
  ],
  brands: [
    { key:'chillout', category:'snacks', color:'#2E2A74', init:{ar:'C',en:'C'}, logo:'images/brands/chillout.webp',
      name:{ar:'شيل آوت', en:'ChillOut'},
      desc:{ar:'سناكس وشيبس مخبوز غير مقلي: أوت شيبس، فاير فينجرز، بوفس، فشار جورميه، وسوداني مغطى.', en:'Baked, never-fried snacks: oat chips, fire fingers, puffs, gourmet popcorn and coated peanuts.'},
      tag:{ar:'سناكس وشيبس', en:'Snacks & Chips'} },
    { key:'special', category:'snacks', color:'#C0392B', init:{ar:'S',en:'S'}, logo:'images/special.webp',
      name:{ar:'سبيشيال', en:'Special'},
      desc:{ar:'بافس مقرمشة بنكهات متنوعة، تعبئة أكياس بأحجام مختلفة تناسب أي رف بيع.', en:'Crunchy puffs in a range of flavours, bagged in multiple sizes for any shelf.'},
      tag:{ar:'بافس', en:'Puffs'} },
    { key:'bozo', category:'snacks', color:'#14123B', init:{ar:'B',en:'B'}, logo:'images/bravo.webp',
      name:{ar:'بوزو', en:'Bozo'},
      desc:{ar:'بافس بنكهات جريئة من علامة برافو، تعبئة أكياس عملية.', en:'Bold-flavoured puffs from the Bravo brand, in practical bag packs.'},
      tag:{ar:'بافس', en:'Puffs'} },
    { key:'crazy', category:'snacks', color:'#D62839', init:{ar:'C',en:'C'}, logo:'images/crazy.webp',
      name:{ar:'كريزي', en:'Crazy'},
      desc:{ar:'كريسبس وفرايدو ذرة مقرمشة بنكهات متعددة من علامة زجزاج.', en:'Crispy corn crisps and Frido snacks in multiple flavours from Zegzag.'},
      tag:{ar:'كريسبس وفرايدو', en:'Crisps & Frido'} },
    { key:'lightpop', category:'candy', color:'#FDB815', init:{ar:'L',en:'L'}, logo:'images/lightpop.webp',
      name:{ar:'لايت بوب', en:'Light Pop'},
      desc:{ar:'مصاصات ولولي بوب بأشكال وتعبئات متعددة (أكياس، شجرة، حافلة، برطمان)، وبونبون وتوفي وإكلير.', en:'Lollipops in bags, jars and display stands, plus bonbon, toffee and eclair candy.'},
      tag:{ar:'مصاصات وحلوى', en:'Lollipops & Candy'} },
    { key:'honeygum', category:'candy', color:'#201C63', init:{ar:'H',en:'H'}, logo:'images/brands/honey.webp',
      name:{ar:'هَني', en:'Honey'},
      desc:{ar:'لبان محشو بنكهات الفاكهة والنعناع، تعبئة علبة وبرطمان.', en:'Center-filled chewing gum in fruit and mint flavours, boxed or jarred.'},
      tag:{ar:'لبان', en:'Chewing Gum'} },
    { key:'mojo', category:'candy', color:'#FFCB4D', init:{ar:'M',en:'M'}, logo:'images/mojo.webp',
      name:{ar:'موجو', en:'MOJO'},
      desc:{ar:'لولي بوب محشو ببابل جم بتصميم كرتوني موجه للأطفال.', en:'Bubble-gum-filled lollipops with playful cartoon packaging for kids.'},
      tag:{ar:'لولي بوب للأطفال', en:"Kids' Lollipops"} },
    { key:'tuttilolly', category:'candy', color:'#4A44A8', init:{ar:'T',en:'T'}, logo:'images/tuttilolly.webp',
      name:{ar:'توتي لولي', en:'Tutti Lolly'},
      desc:{ar:'لولي بوب حجم ميني بخلطة فواكه طبيعية الألوان.', en:'Mini-size lollipops in a natural-colour fruit blend.'},
      tag:{ar:'لولي بوب ميني', en:'Mini Lollipops'} },
    { key:'bravo', category:'candy', color:'#14123B', init:{ar:'B',en:'B'}, logo:'images/bravo.webp',
      name:{ar:'برافو لايت', en:'Bravo Light'},
      desc:{ar:'حلوى صلبة ولبان خاليين تماماً من السكر المضاف.', en:'Sugar-free hard candy and chewing gum, 0% added sugar.'},
      tag:{ar:'خالي من السكر', en:'Sugar-Free'} },
  ],
  products: [
    { name:{ar:'أوت شيبس', en:'Oat Chips'}, brand:{ar:'شيل آوت', en:'ChillOut'}, color:'#2E2A74', category:'snacks',
      details:{ar:'شيبس شوفان مخبوز غير مقلي، بـ70% دهون أقل، مصنوع من حبوب كاملة وغني بالبروتين والألياف.', en:'Baked, never-fried oat chips with 70% less fat, made with whole grains and high in protein and fibers.'},
      flavors:[
        { img:'images/cheese.webp', name:{ar:'جبنة', en:'Cheese'} },
        { img:'images/sweet-lemon.webp', name:{ar:'ليمون حلو', en:'Sweet Lemon'} },
        { img:'images/sour-cream.webp', name:{ar:'قشدة حامضة', en:'Sour Cream'} },
        { img:'images/smokey-bbq.webp', name:{ar:'باربكيو مدخن', en:'Smokey BBQ'} },
        { img:'images/chicken.webp', name:{ar:'دجاج', en:'Chicken'} },
        { img:'images/flamin-hot.webp', name:{ar:'حار لاهب', en:"Flamin' Hot"} },
        { img:'images/grilled-ribs.webp', name:{ar:'ريش مشوية', en:'Grilled Ribs'} },
        { img:'images/sweet-chilli.webp', name:{ar:'شيلي حلو', en:'Sweet Chilli'} },
      ] },
    { name:{ar:'فاير فينجرز', en:'Fire Fingers'}, brand:{ar:'شيل آوت', en:'ChillOut'}, color:'#2E2A74', category:'snacks',
      details:{ar:'مقرمشات ذرة مخفوفة غير مقلية بنكهات حارة جريئة.', en:'Puffed, never-fried corn crisps in bold spicy flavours.'},
      flavors:[
        { img:'images/fire-fingers-spicy-shrimp.webp', name:{ar:'جمبري حار', en:'Spicy Shrimp'} },
        { img:'images/fire-fingers-spicy-salsa.webp', name:{ar:'طاطة حارة', en:'Spicy Salsa'} },
        { img:'images/fire-fingers-spicy-honey.webp', name:{ar:'عسل حار', en:'Spicy Honey'} },
        { img:'images/fire-fingers-spicy-lemon.webp', name:{ar:'ليمون حار', en:'Spicy Lemon'} },
        { img:'images/fire-fingers-spicy-cheese.webp', name:{ar:'جبنة حارة', en:'Spicy Cheese'} },
        { img:'images/fire-fingers-spicy-chicken.webp', name:{ar:'دجاج سامبينج حار', en:'Spicy Chicken'} },
      ] },
    { name:{ar:'كرانشي فينجرز', en:'Crunchy Fingers'}, brand:{ar:'شيل آوت', en:'ChillOut'}, color:'#2E2A74', category:'snacks' },
    { name:{ar:'حلقات الشوفان', en:'Oat Rings'}, brand:{ar:'شيل آوت', en:'ChillOut'}, color:'#2E2A74', category:'snacks' },
    { name:{ar:'سوداني مغطى', en:'Coated Peanuts'}, brand:{ar:'شيل آوت', en:'ChillOut'}, color:'#2E2A74', category:'snacks' },
    { name:{ar:'فشار جورميه', en:'Gourmet Popcorn'}, brand:{ar:'شيل آوت', en:'ChillOut'}, color:'#2E2A74', category:'snacks' },
    { name:{ar:'بافس', en:'Puffs'}, brand:{ar:'شيل آوت', en:'ChillOut'}, color:'#2E2A74', category:'snacks' },
    { name:{ar:'سبيشيال بافس', en:'Special Puffs'}, brand:{ar:'سبيشيال', en:'Special'}, color:'#C0392B', category:'snacks' },
    { name:{ar:'بوزو بافس', en:'Bozo Puffs'}, brand:{ar:'برافو', en:'Bravo'}, color:'#14123B', category:'snacks' },
    { name:{ar:'كريزي كريسبس', en:'Crazy Crisps'}, brand:{ar:'زجزاج', en:'Zegzag'}, color:'#1A1A1A', category:'snacks' },
    { name:{ar:'كريزي فرايدو', en:'Crazy Frido'}, brand:{ar:'زجزاج', en:'Zegzag'}, color:'#D62839', category:'snacks' },
    { name:{ar:'لولي بوب مِكس فليفرز', en:'Lollipop Mix Flavors'}, brand:{ar:'لايت بوب', en:'Light Pop'}, color:'#FDB815', category:'candy' },
    { name:{ar:'لولي بوب فروتس', en:'Fruits Lollipop'}, brand:{ar:'لايت بوب', en:'Light Pop'}, color:'#FDB815', category:'candy' },
    { name:{ar:'بون بون فواكه ولبن', en:'Fruits & Milk Bon Bon'}, brand:{ar:'لايت بوب', en:'Light Pop'}, color:'#FDB815', category:'candy' },
    { name:{ar:'توفي', en:'Toffee'}, brand:{ar:'لايت بوب', en:'Light Pop'}, color:'#FDB815', category:'candy' },
    { name:{ar:'إكلير لايت', en:'Eclair'}, brand:{ar:'لايت بوب', en:'Light Pop'}, color:'#FDB815', category:'candy' },
    { name:{ar:'لولي بوب محشو بابل جم', en:'Bubble Gum Filled Lollipop'}, brand:{ar:'موجو', en:'MOJO'}, color:'#FFCB4D', category:'candy' },
    { name:{ar:'توتي لولي ميني سايز', en:'Mini Size Lollipop'}, brand:{ar:'توتي لولي', en:'Tutti Lolly'}, color:'#4A44A8', category:'candy' },
    { name:{ar:'لبان هَني', en:'Honey Gum'}, brand:{ar:'هَني', en:'Honey'}, color:'#201C63', category:'candy' },
    { name:{ar:'حلوى ولبان خالي من السكر', en:'Sugar-Free Candy & Gum'}, brand:{ar:'برافو لايت', en:'Bravo Light'}, color:'#14123B', category:'candy' },
  ],
  certifications: [
    { name:{ar:'شهادة هالال', en:'HALAL Certified'}, code:'HALAL' },
    { name:{ar:'ISO 22000', en:'ISO 22000'}, code:'FOOD SAFETY' },
    { name:{ar:'ISO 45001', en:'ISO 45001'}, code:'HEALTH & SAFETY' },
    { name:{ar:'ISO 9001', en:'ISO 9001'}, code:'QUALITY MGMT' },
    { name:{ar:'HACCP', en:'HACCP'}, code:'HAZARD CONTROL' },
    { name:{ar:'اعتماد FDA', en:'FDA Registered'}, code:'US MARKET' },
  ],
  reach: [
    { name:{ar:'أوروبا (6)', en:'Europe (6)'},
      value:{ar:'السويد، ألمانيا، فرنسا، هولندا، بلجيكا، النرويج', en:'Sweden, Germany, France, Netherlands, Belgium, Norway'} },
    { name:{ar:'أفريقيا (6)', en:'Africa (6)'},
      value:{ar:'ليبيا، المغرب، مدغشقر، جنوب أفريقيا، السودان، كينيا', en:'Libya, Morocco, Madagascar, South Africa, Sudan, Kenya'} },
    { name:{ar:'الشرق الأوسط وآسيا (14)', en:'Middle East & Asia (14)'},
      value:{ar:'الإمارات، قطر، تركيا، لبنان، البحرين، العراق، عمان، الأردن، فلسطين، اليمن، السعودية، الكويت، الهند، سوريا', en:'UAE, Qatar, Turkey, Lebanon, Bahrain, Iraq, Oman, Jordan, Palestine, Yemen, Saudi Arabia, Kuwait, India, Syria'} },
    { name:{ar:'أمريكا (2)', en:'Americas (2)'},
      value:{ar:'الولايات المتحدة، كوبا', en:'United States, Cuba'} },
  ],
  leadership: [
    { name:{ar:'[الاسم]', en:'[Name]'}, title:{ar:'رئيس مجلس الإدارة التنفيذي', en:'Executive Chairman'}, init:'A' },
    { name:{ar:'[الاسم]', en:'[Name]'}, title:{ar:'المدير العام', en:'General Manager'}, init:'B' },
    { name:{ar:'[الاسم]', en:'[Name]'}, title:{ar:'نائب رئيس مجلس الإدارة', en:'Vice Chairman'}, init:'C' },
    { name:{ar:'[الاسم]', en:'[Name]'}, title:{ar:'عضو مجلس إدارة منتدب', en:'Managing Board Member'}, init:'D' },
    { name:{ar:'[الاسم]', en:'[Name]'}, title:{ar:'عضو مجلس إدارة مستقل', en:'Independent Board Member'}, init:'E' },
    { name:{ar:'[الاسم]', en:'[Name]'}, title:{ar:'عضو مجلس إدارة مستقل', en:'Independent Board Member'}, init:'F' },
  ],
  partners: [
    { name:{ar:'[اسم الشريك]', en:'[Partner]'} },
    { name:{ar:'[اسم الشريك]', en:'[Partner]'} },
    { name:{ar:'[اسم الشريك]', en:'[Partner]'} },
    { name:{ar:'[اسم الشريك]', en:'[Partner]'} },
    { name:{ar:'[اسم الشريك]', en:'[Partner]'} },
    { name:{ar:'[اسم الشريك]', en:'[Partner]'} },
    { name:{ar:'[اسم الشريك]', en:'[Partner]'} },
    { name:{ar:'[اسم الشريك]', en:'[Partner]'} },
  ],
};
